# Generated by Django 5.0 on 2023-12-30 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='slots_available',
            new_name='available_slots',
        ),
    ]
